version: "3"
services:
    employee-db:
        image: mysql
        restart: always
        env_file: ./.env
        networks:
            - dbxnode
        hostname: 0.0.0.0
        ports:
            - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DABASE
        volumes:
            - mysqldb:/database
volumes:
    mysqldb:
networks:
    dbxnode:
        name: dbxnode
        driver: bridge